version: '3'
services:
  db:
    container_name: dhis-db
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    ports:
    - "5433:5432"
  web:
    container_name: dhis-web
    image: dhis2/core:2.33.0
    volumes:
    - ./dhis.conf:/DHIS2_home/dhis.conf
    ports:
    - "8088:8080"
    depends_on:
    - db